# Generated by Django 5.0.6 on 2024-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('important', models.BooleanField(default=False)),
                ('urgently', models.BooleanField(default=False)),
                ('todo_date', models.DateField(default='2024-06-01')),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
