# Generated by Django 5.0.6 on 2024-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
